define LOCAL_ASN = 151673;
define LOCAL_V6_kernel = 2a14:7581:381;
#define LOCAL_V4_kernel = 1.1.1.1;
#define BB_V4_Prefix = 1.1.1.0/24;
#define BB_V4 = 1.1.1.1;
#define BB_V4_Prefix_check = [2a0f:7803:fcaa::/48{128,128}];
#define BB_OSPF_V4 = ;
define BB_V6 = 2a14:7581:381;
define BB_OSPF_V6 = 2a14:7581:381/128;
define BB_V6_Prefix = 2a14:7581:3810::/44;
define BB_V6_Prefix_check = [2a14:7581:3810::/44{128,128}];
define MY_COMMUNITY = 151673;
define MY_REGION = ;
define MY_COUNTRY = ;
define MY_NODE = 1;

router id ;


function kernel_route_hack(){
}
